config/routes.rb
Ncia::Application.routes.draw do

	get "/feed" => "articles#feed", as: :rss_feed, :defaults => { :format => 'rss' }

	get "/nesymposium" => "pages#nesymposium"
	get "/nesymposiumagenda" => "pages#nesymposiumagenda"
	get "/nesymposiumspeakers" => "pages#nesymposiumspeakers"

	get "/blogs/admin_index" => "blogs#admin_index"
  resources :blogs

	match 'join' => 'users#new', as: :join
	get   'users/payment' => 'users#payment', as: :payment
	match 'users/activate/:activation' => 'users#activate', as: :activate_user
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users, except: [:show]
	put "passwords/execute" => "password_resets#execute", as: "update_password_while_logged_in"
	resources :password_resets, only: [:create, :edit, :update, :new]

	post "members/search_index" => "members#search_index", as: "members_search_index"
	get "members/discounts" => "members#discounts", as: "member_discounts"
	post "members/discounts" => "members#discounts_search", as: "member_discounts_search"
	get "members/admin_index" => "members#admin_index"
	get "members/portal/:id" => "members#portal_show", as: "members_portal_show"
  resources :members

  resources :staffs, except: [:index, :show]
	get "staffs/staff" => "staffs#staff_index", as: :staff_index
	get "staffs/board" => "staffs#board_index", as: :board_index
	get "staffs/admin_index" => "staffs#admin_index"

  resources :events, except: [:show]
	get "/events/admin_index" => "events#admin_index"

  resources :contact_messages, only: [:create, :destroy]
	get "contact_messages/admin_index" => "contact_messages#admin_index"

  resources :articles, except: [:show]
	get "/articles/admin_index" => "articles#admin_index"
	get "/articles/:title" => "articles#show"

  root :to => 'pages#home'

	resources :banners, :only => [:new, :create, :edit, :update, :destroy]
	get "/banners/admin_index" => "banners#admin_index", as: :banners_admin_index
	get "/banners/:id/activate" => "banners#activate", as: :activate_banner

	resources :uploads, :only => [:new, :create, :destroy]
	get "/uploads/admin_index" => "uploads#admin_index", as: :uploads_admin_index

	get  '/:title' => 'pages#show', as: "pages"
	get  'pages/:title/edit' => 'pages#edit'
	put  'pages/:title'      => 'pages#update'

end

app/models/staff.rb
class Staff
  include Mongoid::Document
	include Mongoid::Paperclip
	include Mongoid::Timestamps

  field :name, type: String
  field :title, type: String
  field :bio, type: String
  field :type, type: Integer

	attr_accessible :name, :title, :bio, :type, :image
	has_mongoid_attached_file :image, :styles => { :thumb => '125X' }

	 def type=(input)
    new_type = case input
      when ( 'staff' )
        0
      when ( 'board' )
        1
      else
        0
    end
    write_attribute(:type, new_type)
  end
  
  def type
    t = read_attribute(:type)
    case t
      when 0
        'staff'
      when 1
        'board'
			else
				'staff'
		end
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

	before_filter :require_admin, except: [:staff_index, :board_index]

	def staff_index
		@people = Staff.where( type: 0 )
		render "index"
	end	

	def board_index
		@people = Staff.where( type: 1 )
		render "index"
	end

	def admin_index
		@people = Staff.all
		render layout: "backend"
	end

	def new
		@person = Staff.new
		render layout: "backend"
	end

	def create
		@person = Staff.new( params[:staff] )
		if @person.save
			redirect_to staffs_admin_index_path
		else
			render "new"
		end
	end

	def edit
		@person = Staff.find( params[:id] )
		render layout: "backend"
	end

	def update
		@person = Staff.find( params[:id] )
		if @person.update_attributes( params[:staff] )
			redirect_to staffs_admin_index_path
		else
			render "edit"
		end
	end

	def destroy
		Staff.find( params[:id] ).destroy
	end

end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= tinymce_assets %>

<%= simple_form_for person, :html => {:multipart => true} do |f| %>
  <%= f.input :name %>
  <%= f.input :title %>
	<%= f.input :bio, as: :text, :input_html => { class: 'tinymce text-edit' } %>
	<%= f.input :type, :collection => ["staff", "board"] %>
	<%= f.file_field :image %>
	<br />
  <%= f.button :submit %>
<% end %>

<%= tinymce %>

app/views/staffs/admin_index.html.erb
<%= link_to "Create New", new_staff_path %>

<% @people.each do |p| %>
	<ul class="admin-index">		
		<li><%= p.name %></li>
		<li><%= p.type %></li>
		<li><%= link_to "Edit", edit_staff_path( p ) %></li>
		<li><%= link_to "Delete", staff_path( p ), confirm: "Are you sure?", method: :delete %></li>
	</ul>
<% end %>

app/views/staffs/edit.html.erb
<%= render "form", person: @person %>

app/views/staffs/index.html.erb
<% if @people.empty? %>
	<p>Sorry no entries at this time we will have them up very soon!</p>
<% end %>

<% @people.each do |p| %>
	<div class="bio-container">
		<h4 class="bio"><%= "#{p.name}, #{p.title}" %></h4>
		<p class="bio">
			<%= image_tag p.image.url(:thumb), class: "bio" %>
			<%= raw p.bio %>
		</p>
	</div>
<% end %>

app/views/staffs/new.html.erb
<%= render "form", person: @person %>