config/routes.rb
Ncia::Application.routes.draw do

	get "/feed" => "articles#feed", as: :rss_feed, :defaults => { :format => 'rss' }

	get "/nesymposium" => "pages#nesymposium"
	get "/nesymposiumagenda" => "pages#nesymposiumagenda"
	get "/nesymposiumspeakers" => "pages#nesymposiumspeakers"

	get "/blogs/admin_index" => "blogs#admin_index"
  resources :blogs

	match 'join' => 'users#new', as: :join
	get   'users/payment' => 'users#payment', as: :payment
	match 'users/activate/:activation' => 'users#activate', as: :activate_user
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users, except: [:show]
	put "passwords/execute" => "password_resets#execute", as: "update_password_while_logged_in"
	resources :password_resets, only: [:create, :edit, :update, :new]

	post "members/search_index" => "members#search_index", as: "members_search_index"
	get "members/discounts" => "members#discounts", as: "member_discounts"
	post "members/discounts" => "members#discounts_search", as: "member_discounts_search"
	get "members/admin_index" => "members#admin_index"
	get "members/portal/:id" => "members#portal_show", as: "members_portal_show"
  resources :members

  resources :staffs, except: [:index, :show]
	get "staffs/staff" => "staffs#staff_index", as: :staff_index
	get "staffs/board" => "staffs#board_index", as: :board_index
	get "staffs/admin_index" => "staffs#admin_index"

  resources :events, except: [:show]
	get "/events/admin_index" => "events#admin_index"

  resources :contact_messages, only: [:create, :destroy]
	get "contact_messages/admin_index" => "contact_messages#admin_index"

  resources :articles, except: [:show]
	get "/articles/admin_index" => "articles#admin_index"
	get "/articles/:title" => "articles#show"

  root :to => 'pages#home'

	resources :banners, :only => [:new, :create, :edit, :update, :destroy]
	get "/banners/admin_index" => "banners#admin_index", as: :banners_admin_index
	get "/banners/:id/activate" => "banners#activate", as: :activate_banner

	resources :uploads, :only => [:new, :create, :destroy]
	get "/uploads/admin_index" => "uploads#admin_index", as: :uploads_admin_index

	get  '/:title' => 'pages#show', as: "pages"
	get  'pages/:title/edit' => 'pages#edit'
	put  'pages/:title'      => 'pages#update'

end

app/views/shared/_agreement.html.erb
<p><i>This voluntary industry code of conduct sets out specific standards of conduct for members of the national cannabis industry with respect to the manner in which they deal with other members and their customers. All NCIA members agree to adhere to this code as a condition of membership.</i></p>
<p>The National Cannabis Industry Association (NCIA) recognizes that the manner in which members conduct business reflects upon the professionalism of the entire cannabis industry. Therefore, upon acceptance into membership, NCIA requests that members abide by the NCIA Pledge and Code of Conduct in word, action, and with the spirit of integrity that is at the core of these principles.</p>
<p>Members of the National Cannabis Industry Association demonstrate their commitment to the profession, to society and to their peers by pledging to uphold and abide by the following standards:</p>
<p>We shall conduct ourselves and our businesses in an honest and dignified manner, reflecting our adherence to the laws that govern our operations.</p>
<p>Given the high profile of the cannabis industry and the scrutiny under which we operate, we commit to appearing and acting professionally in order to reflect a positive image for the industry and promote our profession.</p>
<p>We will strive to educate ourselves, our constituents, and our clients about the most current research and practices available to the industry.</p>
<p>We agree that safety, training, and education are of the utmost importance in maintaining a professional workforce. We pledge to provide for the safety and training of employees to ensure a healthy work environment. We will endeavor to grow our work force through training and employee development.</p>
<p>We shall respect the views, ideas and contributions of our peers. Open and honest communications and the sharing of ideas and experiences are critical components in the early development of the cannabis industry.</p>
<p>To the greatest extent possible, we shall obtain and maintain all state and local licenses required by applicable state and local law to engage in any aspect of the cannabis industry.</p>
<p>We recognize the precarious nature of the existing laws and regulations and pledge to support political activity that advances the legitimization of the industry -- both through their support of NCIA and through support of local efforts.</p>
<p>We commit to advertising in a manner that reflects positively on the cannabis industry and shall comply with all truth-in-advertising standards.</p>
<p>We shall treat NCIA members with honesty, respect, integrity, and good faith.</p>
<p>Members shall express opinions about other members and the products they offer in a fashion that will facilitate a collegial, professional, and productive atmosphere within the organization. Members shall further avoid conflicts of interest, predatory practices, and anti-competitive behavior.</p>
<p>Each NCIA member not only agrees to abide by the principles and practices set forth in this Code of Conduct, but also acknowledges that a material violation of any of the provisions of this Code could constitute grounds for immediate removal from the organization.</p>

app/views/shared/_alerts.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert success">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <div class="row">
		<div class="span8">
        <%= content_tag :div, flash[:notice] %>
		</div>
    </div>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert success">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <div class="row">
		<div class="span8">
        <%= content_tag :div, flash[:error] %>
    </div>
		</div>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert success">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <div class="row">
		<div class="span8">
        <%= content_tag :div, flash[:alert] %>
    </div>
		</div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
	<ul class="main-menu">
		<li><%= link_to "Home", root_path %></li>
		<li class="cust-drop-down-link"><%= link_to "About Us", "#" %>
			<ul class="main-menu-drop-down">
				<li><%= link_to "Mission and Vision", "/aboutus" %></li>
				<!-- <li><%= link_to "Board", board_index_path %></li> -->
				<li><%= link_to "Staff", staff_index_path %></li>
				<li><%= link_to "Contact", "/contact" %></li>
			</ul>
		</li>
		<li><%= link_to "Member Directory", members_path %></li>
		<li class="cust-drop-down-link"><%= link_to "Member Benefits", "#" %>
			<ul class="main-menu-drop-down">
				<li><%= link_to "Industry Advocacy", "/industryadvocacy" %></li>
				<li><%= link_to "Member Discounts", member_discounts_path %></li>
				<li><%= link_to "Events", events_path %></li>
				<% link = (logged_in? ? members_portal_show_path( current_user ) : login_path) %>
				<!-- <li><%= link_to "Member Portal", link %></li> -->
			</ul>
		</li>
		<li><%= link_to "Campaigns", "/campaigns" %></li>
		<li><%= link_to "News", articles_path %></li>
		<li><%= link_to "Join", join_path %></li>
	</ul>
	<h1 class="main-title">The National Voice for the<br />Cannabis Industry</h1>
	<div class="social-container">
		<%= link_to( image_tag("facebook.png"), "https://www.facebook.com/TheNCIA" ) %>
		<%= link_to( image_tag("twitter.png"), "http://twitter.com/NCIAorg" ) %>
		<%= link_to( image_tag("rss.png"), "https://www.facebook.com/TheNCIA" ) %>
	</div>
</div>

app/views/shared/_map.html.erb
<iframe width="350" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=<%= address %>&amp;aq=0&amp;ie=UTF8&amp;hq=&amp;hnear=<%=  address %>&amp;t=m&amp;z=14&amp;output=embed"></iframe>

app/views/shared/_member-descriptions.html.erb
<div class="member-level bronze">
<h4>REGULAR MEMBERSHIP</h5>
<p>Dues: $1,000 annually or a $100 monthly pledge.</p>
<p>This is a basic membership plan that includes national representation for your business, promotional listing in association materials and eligibility for member discounts.</p>
</div>

<div class="member-level silver">
<h4>SPONSORING MEMBERSHIP</h5>
<p>Dues: $2,500 annually or a $250 monthly pledge.</p>
<p>This preferred membership plan grants eligibility to vote in NCIA board elections and includes all to the benefits of a Regular Membership.</p>
</div>

<div class="member-level gold">
<h4>SUSTAINING MEMBERSHIP</h5>
<p>Dues: Beginning at $5,000 annually or a $500 monthly pledge.</p>
<p>This premium membership plan includes eligibility to serve on the NCIA board of directors, access to exclusive industry events, high-profile listing in association materials, and all to the benefits of a Sponsoring Membership.</p>
</div>