config/routes.rb
Ncia::Application.routes.draw do

	get "/feed" => "articles#feed", as: :rss_feed, :defaults => { :format => 'rss' }

	get "/nesymposium" => "pages#nesymposium"
	get "/nesymposiumagenda" => "pages#nesymposiumagenda"
	get "/nesymposiumspeakers" => "pages#nesymposiumspeakers"

	get "/blogs/admin_index" => "blogs#admin_index"
  resources :blogs

	match 'join' => 'users#new', as: :join
	get   'users/payment' => 'users#payment', as: :payment
	match 'users/activate/:activation' => 'users#activate', as: :activate_user
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users, except: [:show]
	put "passwords/execute" => "password_resets#execute", as: "update_password_while_logged_in"
	resources :password_resets, only: [:create, :edit, :update, :new]

	post "members/search_index" => "members#search_index", as: "members_search_index"
	get "members/discounts" => "members#discounts", as: "member_discounts"
	post "members/discounts" => "members#discounts_search", as: "member_discounts_search"
	get "members/admin_index" => "members#admin_index"
	get "members/portal/:id" => "members#portal_show", as: "members_portal_show"
  resources :members

  resources :staffs, except: [:index, :show]
	get "staffs/staff" => "staffs#staff_index", as: :staff_index
	get "staffs/board" => "staffs#board_index", as: :board_index
	get "staffs/admin_index" => "staffs#admin_index"

  resources :events, except: [:show]
	get "/events/admin_index" => "events#admin_index"

  resources :contact_messages, only: [:create, :destroy]
	get "contact_messages/admin_index" => "contact_messages#admin_index"

  resources :articles, except: [:show]
	get "/articles/admin_index" => "articles#admin_index"
	get "/articles/:title" => "articles#show"

  root :to => 'pages#home'

	resources :banners, :only => [:new, :create, :edit, :update, :destroy]
	get "/banners/admin_index" => "banners#admin_index", as: :banners_admin_index
	get "/banners/:id/activate" => "banners#activate", as: :activate_banner

	resources :uploads, :only => [:new, :create, :destroy]
	get "/uploads/admin_index" => "uploads#admin_index", as: :uploads_admin_index

	get  '/:title' => 'pages#show', as: "pages"
	get  'pages/:title/edit' => 'pages#edit'
	put  'pages/:title'      => 'pages#update'

end

app/views/widgets/_articles.html.erb
<% articles = Article.order_by( [[:created_at, :desc ]] ).limit(3) %>

<h3 class="article-widget">Cannabis Industry News:</h3>
<ul class="article-widget">
	<% articles.each do |a| %>
		<li class="articles-widget"><%= link_to a.title, article_path(a), class: 'article-widget' %></li>
	<% end %>
</ul>

<div class="news-links">
	<span class="more-news-link">More news</span><%= link_to( image_tag( "news-arrow.jpg", class: "news-arrow" ), articles_path ) %>
</div>

<%= link_to( image_tag( "newspaper.jpg", class: "newspaper" ), articles_path ) %>

app/views/widgets/_donate.html.erb
<div class='donate join'>

<script>
function checkval () {
var amount = document.getElementById('ItemCost').value; 
amount= amount.replace(/[^.0-9]+/g,'');
document.getElementById('ItemCost').value = amount; 
var amount2 = parseFloat(amount); if (amount2 < 25){alert("We apologize, but donations must be greater than or equal to $25 (Twenty Five Dollars)."); return false;}else{return true;}
}
</script>


<form action="https://www.eprocessingnetwork.com/cgi-bin/wo/order.pl" method="post" onSubmit="return checkval();">
	<h2 class="donate">Donate Today!<br />$
	<input type="text" name="ItemCost" id="ItemCost" value="" size=8 maxlength=8 style='width:80px;'>
	<input type=hidden name="QB" value="">
	<input type="hidden" name="ItemQty" value="1"><input type="hidden" name="ItemDesc" value="Donation"><input <input type="submit" value="Donate">
	<input type="hidden" name="ePNAccount" value="0211625">
	<input type="hidden" name="ReturnToURL" value="http://www.thecannabisindustry.org">
	<input type="hidden" name="BackgroundColor" value=#FDFDD6>
	<input type="hidden" name="TextColor" value=#000000>
	<input type="hidden" name="LogoURL" value="http://cannapages.com/colorado/files/2011/05//41801_131429140247116_3724480_n.jpg">
	<input type="hidden" name="LogoPosition" value="left"></h2>
</form>

</div>

app/views/widgets/_join.html.erb
<div class="join">
	<h3 class="join">Enjoy Strength in Numbers</h3>
	<div class="ncia-btn"><h4 class="join"><%= link_to "JOIN TODAY", join_path %></h3></div>
</div>

app/views/widgets/_members.html.erb
<% total = @members_banner.size %>
<% count = 1 %>
<div class="member-widget">
	<% @members_banner.each do |m| %>
		<% next if File.basename( m.image.url(:thumb)) == "missing.png" %>
		<% member_class = "member-widget" %>
		<% member_class += " hidden" if count > 5 %>
		<%= link_to( image_tag( m.image.url(:thumb), class: member_class, "data-index" => count ), m.website || "#" ) %>
		<% count += 1 %>
	<% end %>
	<div class="ncia-btn-large"><h4 class="member-widget"><%= link_to "MEMBER DIRECTORY", members_path %></h3></div>
</div>

<div id="member-laston" data-value=5></div>
<div id="member-count" data-value=<%= total %>></div>